config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homes#latest'
  resources :articles do
    resources :comments, only:[:create]
    resources :votes
  end
  resources :my_articles, only: [:index]

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  has_many :votes
  has_attached_file :image , styles: { large: "600x600>", medium: "300x300>", thumb: "150x150#"}
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  def like_count
  	votes.where(value: 1).count
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  belongs_to :user
  has_many :votes
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :articles
  has_many :comments
  has_many :votes
  
end

app/models/vote.rb
class Vote < ActiveRecord::Base
	belongs_to :article
	belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def check_user_signed_in
    if current_user == nil
      redirect_to new_user_session_path, alert: 'Phải đăng nhập trước'
    end
  end
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
 before_action :check_user_signed_in, except: [:show]

  def new
  	@article = Article.new
  end

  def create
  	@article = Article.new(params.require(:article).permit(:title, :content, :image))
    @article.user = current_user
  	if @article.save
  		redirect_to root_path
  	else
  		render :new
  	end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(aritcle_params)
      redirect_to root_path
    else
      render :edit
    end 
  end

  def aritcle_params
    params.require(:article).permit(:title, :content, :image)
  end

  def show
    @article = Article.find(params[:id])
    @comment = Comment.new
    @comments = @article.comments
  end

  def delete
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to root_path
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to root_path
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  before_action :check_user_signed_in

    def create
      @article = Article.find(params[:article_id])
      @comment = Comment.new(params.require(:comment).permit(:content))
      @comment.user = current_user
      @comment.article = @article

    if @comment.save
      redirect_to article_path(@article) 
    else
        redirect_to article_path(@article), alert: 'Bình luận không hợp lệ'
    end
    
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def latest
  	@article = Article.order('created_at DESC').limit(5)
  end
  
end

app/controllers/my_articles_controller.rb
class MyArticlesController < ApplicationController
  before_action :check_user_signed_in

  def index
    @articles = current_user.articles
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :check_user_signed_in

	def create
		article = Article.find(params[:article_id])
		vote = Vote.where(user_id: current_user.id, article_id: article.id).first
		if vote == nil
			vote = Vote.new(params.require(:vote).permit(:value))
			vote.user = current_user
			vote.article = article
			vote.save!
		end
		redirect_to article_path(article)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<%= form_for @article, html: {multipart: true } do |f| %>

<div class="field">
<%= f.label :image %><br>
<%= f.file_field :image%>
</div>

  <div>
    <% if @article.errors[:title].length > 0 %>
      <p><%= @article.errors[:title][0] %></p>
    <% end %>
    <%= f.label :title %>
  </div>

  <div>
    <%= f.text_field :title %>
  </div>

  <div>
    <% if @article.errors[:content].length > 0 %>
      <p><%= @article.errors[:content][0] %></p>
    <% end %>
    <%= f.label :content  %>
  </div>

  <div>
    <%= f.text_area :content, size: "60x12" %>
  </div>

  <div>
    <% if @article.new_record? %>
      <%= f.submit "create" %>
    <% else %>
      <%= f.submit "update" %>
    <%end%>
  </div>
      
<% end %>

app/views/articles/_index.html.erb
<% @article.each do |article|%>

  <h2><%= article.title %></h2>
   
  <div>
   <%= image_tag article.image.url(:thumb)%>
  </div>
  
  <div>
    <%= article.content %>
  </div>

  <div>
    <%= link_to 'Chi tiết', article_path(article)%>
    <% if user_signed_in? %>
      <% if current_user == article.user %>
        <div class="article-info">
          <%= link_to 'Edit', edit_article_path(article)%>
          <%= link_to 'delete', article_path(article), method: 'delete', data: {confirm: 'Bạn có muốn xoá bài này không?'} %>
        </div> 
      <%end%> 
    <%end%>
  </div>

<%end%>

app/views/articles/edit.html.erb
<h2> Sua bai viet <%= @article.title%></h2>
<%= render 'form' %>

app/views/articles/index.html.erb
<% @article.each do |article|%>

   <h2><%= article.title %></h2>
   
   <div>
   <%= article.content %>
   </div>

   <div>
    <%= link_to 'chi tiet', article_path(article)%>
    <%if user_signed_in?%>
    <%= link_to 'Edit', edit_article_path(article)%>
    <%= link_to 'delete', article_path(article), method: 'delete', data: {confirm: 'ban co muon xoa?'} %>
    <%end%>
   </div>



<%end%>

app/views/articles/new.html.erb
<%=render 'form' %>

app/views/articles/show.html.erb
<div class="article-title">
<%= @article.title%>
</div>

<%= image_tag @article.image.url(:large) %>

<div class="article-content">
  <%= @article.content %>
</div>



<%if current_user == @article.user%>
	<div class="article-info">
	  <%= link_to 'Edit', edit_article_path(@article)%>
	</div>
<%end%>

<div class="vote">
	<p>
	<div class="btn-group" role="group" aria-label="...">
  	<%= link_to article_votes_path(@article, vote: {value: 1}), class:"btn btn-danger btn-lg", method: :post do %>
		  <span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span><%= @article.like_count %>
 	<% end %>
		<button type="button" class="btn btn-default btn-lg">
  <span class="glyphicon glyphicon-thumbs-down" aria-hidden="true"></span>1
	</button>
</div>
	
	</p>

<div class="comment-form">
  <%= form_for [@article, @comment] do |f|%>
    <%=f.text_area :content%>
    <%=f.submit 'Lưu'%>
  <%end%>
</div>

<div class="comments">
<p>Có <%= @comments.count %> bình luận:</p>
	<% @comments.each do |comment|%>
	  <div>
	     <%= comment.content %>
	  </div>
	  <div class="comment-info">
      Bởi <%= comment.user.email %>, cách đây <%= time_ago_in_words(comment.created_at)%>
    </div>
	<% end %>


</div>
</div>


     

app/views/homes/latest.html.erb
<%= render 'articles/index'%>

app/views/layouts/_footer.html.erb
<div class="container" style="margin-top: 100px">
  <footer>
    <p>&copy; 2016 lhvu, Inc.</p>
  </footer>
</div> <!-- /container -->

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">

      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%=link_to 'HaiVL - Vu', root_path, class: 'navbar-brand'%>
        </div>

        <ul class="nav navbar-nav navbar-right">

          <%if user_signed_in?%>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                 <%= current_user.email %><span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li>
                  <%= link_to edit_user_registration_path do %>
                    <span class="glyphicon glyphicon-user"></span> Cập nhật thông tin cá nhân
                  <% end %>
                </li>

                <li>
                  <%= link_to new_article_path do %>
                    <span class="glyphicon glyphicon-pencil"></span> Đăng bài
                  <% end %>
                </li>

                <li>
                  <%= link_to my_articles_path do %>
                    <span class="glyphicon glyphicon-th-list"></span> Quản lý bài viết
                  <% end %>
                </li>

                <li role="separator" class="divider"></li>

                <li>
                  <%= link_to destroy_user_session_path, method: :delete do %>
                    <span class="glyphicon glyphicon-log-out"></span> Đăng xuất
                  <% end %>
                </li>
               </ul>
            </li>

          <%else%>
            <div class="btn navbar-btn navbar-right">
              <%=link_to 'Đăng Ký', new_user_registration_path, class: "btn btn-default btn-sm"%>                  
              <%=link_to 'Đăng Nhập', new_user_session_path, class: "btn btn-success btn-sm"%>
            </div>
          <%end%>
        </ul>

      </div>

    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    

    <title>Haivl</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

  </head>

  <body>


    <%= render 'layouts/header' %><br/><br/><br/><br/>

    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="container">
      <div class="row">

        <div class="col-sm-8 blog-main">
          
            
              <div>
              <p class="notice"><%= notice %></p>
              <p class="alert"><%= alert %></p>
              </div>
              <%= yield %>
            
        </div>
        <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
          <div class="sidebar-module sidebar-module-inset">
            <h4>Bài viết hay nhất</h4>
          </div>

          <div class="sidebar-module">
            <h4>Video hay nhất</h4>
          </div>
        </div><!-- /.blog-sidebar -->

      </div><!-- /.row -->

    </div><!-- /.container -->
    <%= render 'layouts/footer' %>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
  </body>
</html>

app/views/my_articles/index.html.erb
<h2>Quản lý bài viết</h2>
<table class="table table-striped">
  <thead>
    <th>ID</th>
    <th>Tiêu đề</th>
    <td></th>
  </thead>
  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.id %></td>
        <td><%= article.title %></td>
        <td>
          <%= link_to 'Xem', article_path(article), class: 'btn btn-default btn-sm' %>
          <%= link_to 'Sửa', edit_article_path(article), class: 'btn btn-warning btn-sm' %>
          <%= link_to 'Xoá', article_path(article), method: :delete, data: { confirm: 'Bạn có muốn xoá bài này không?' }, class: 'btn btn-danger btn-sm' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>